### ISSUE TITLE
Cursor is really hard to see when used with the Vim plugin

### ISSUE THREAD

**Issue by jamesgecko** [kevinsawicki/monokai#10]
When using the Vim plugin in command mode, the cursor is invisible, only the text highlight may be seen. This makes it a lot harder to tell where the cursor is, especially because it means that the cursor is invisible when it's over whitespace.

![screenshot 2014-03-10 10 01 50](https://f.cloud.github.com/assets/44252/2374226/90342fd6-a85c-11e3-932e-d310dbcdcc40.png)

**Comment by svanharmelen** [comment]
@jamesgecko it's been a while so before diving into this one, could you let me know if this is still an issue, or that it is solved in the mean time?

Thanks!

**Comment by jamesgecko** [comment]
Looks to be resolved.
