### ISSUE TITLE
Wrong color on preprocessing directive.

### ISSUE THREAD

**Issue by ivan0kurnia** [kevinsawicki/monokai#104]
`#define LED1 2`

Color of `LED1` shouldn't have the same color as the `2`.

![image](https://user-images.githubusercontent.com/2723957/54422959-91284c00-474a-11e9-80d7-45953df79394.png)
How it looks in your theme.

![image](https://user-images.githubusercontent.com/2723957/54423015-a7cea300-474a-11e9-923f-2bd3d37f6936.png)
Visual Studio Code: how it should look.

**Comment by gustavoalfaro** [comment]
Can you provide more information?
