### ISSUE TITLE
Does not work with CoffeeScript Preview package

### ISSUE THREAD

**Issue by jordanbtucker** [kevinsawicki/monokai#19]
This theme does not highlight the preview pane in [CoffeeScript Preview][csp] like the [Atom Dark syntax theme][ad] does. This is because the [`.editor` block][ml8] encompasses the entire stylesheet, whereas preview panes are not `.editor` panes.

I commented out lines [8][ml8] and [187][ml187], and it seems to be working without issue. Although, it would probably be best to model after the Atom Dark theme, where everything starting with line [105][adl105] is not within the `.editor` block.

[csp]: https://atom.io/packages/coffeescript-preview
[ml8]: https://github.com/kevinsawicki/monokai/blob/v0.7.0/index.less#L8
[ml187]: https://github.com/kevinsawicki/monokai/blob/v0.7.0/index.less#L187
[ad]: https://github.com/atom/atom-dark-syntax
[adl105]:https://github.com/atom/atom-dark-syntax/blob/v0.19.0/index.less#L105

**Comment by svanharmelen** [comment]
@jordanbtucker I know this is quite an old issue, but if I test this now with the [preview](https://atom.io/packages/preview) package, it works as expected. Could you confirm that it also works for you so we can close this issue?

**Comment by jordanbtucker** [comment]
If it works for, then that's good enough for me. CoffeeScript Preview has been deprecated in favor of Atom Preview for a long time.
