### ISSUE TITLE
Antialiased fonts

### ISSUE THREAD

**Issue by loureirorg** [kevinsawicki/monokai#20]
Hi, why not use anti-aliased fonts, like this:

https://discuss.atom.io/t/atom-font-weight-anti-alias/4212/2

In my index.less I added the above line inside the .editor (index.less file):
```less
-webkit-font-smoothing: subpixel-antialiased;
```

Also, in my Ubuntu, the default font for Sublime is this:
```coffee
'fontSize': 17
'fontFamily': 'DejaVu Sans Mono'
```

I don't know if on different SO's Sublime has this same schema, but if have, maybe will be interesting to have this same set.

**Comment by braver** [comment]
`-webkit-font-smoothing: auto` already picks the best option for your selected font. In many cases it will be `subpixel-antialiased`. It could be that for some fonts, in some cases, for some users one some platforms, `aliased` actually looks better. It depends on a lot of thing, primarily on the font. It makes no sense to mess with anything related to font-rendering in a syntax theme. 

Same goes for other font related settings, it's a user setting that has nothing to do with the syntax theme. Also, DejaVu isn't available on most systems, so it's not part of the default font stack for Atom.
