### ISSUE TITLE
Add some ways to see which brackets is selected

### ISSUE THREAD

**Issue by KeitIG** [kevinsawicki/monokai#26]
With the Atom Dark Theme, you can see by placing your cursor near a bracket, the next closing bracket.

![capture du 2014-12-17 17 28 00](https://cloud.githubusercontent.com/assets/1311607/5474491/3517413a-8612-11e4-92a7-a361cb9fafbc.png)

![capture du 2014-12-17 17 28 44](https://cloud.githubusercontent.com/assets/1311607/5474494/36bf1382-8612-11e4-9898-240a73dacc12.png)

I would enjoy to see this with this monokai theme.

**Comment by Traverse** [comment]
Is this still an issue, because they're getting highlighted for me.
![example2](https://cloud.githubusercontent.com/assets/7240988/5773975/fc98b0f0-9d68-11e4-929b-07adc2a486da.png)
![example1](https://cloud.githubusercontent.com/assets/7240988/5773976/fc9a57e8-9d68-11e4-99a9-8f3e87d2654e.png)

**Comment by KeitIG** [comment]
Now they're highlighting, I must have missed an update. Thanks !
