### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by Bendraneu** [kevinsawicki/monokai#28]
According to Atom 0.174, the latest version 0.10 of the monikai theme uses some outdated selectors:

monokai
index.less
Use the `atom-text-editor` tag instead of the `editor-colors` class.
Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by NSElvis** [comment]
This was fixed on 0.11

**Comment by kevinsawicki** [comment]
Yup, please upgrade.
