### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by samarpanda** [kevinsawicki/monokai#33]
In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by kevinsawicki** [comment]
Upgrade to version 0.12 of this theme.

**Comment by djhojd** [comment]
I'm on monokai@0.16.0 with atom 1.0.0 and I'm getting this deprecation message starting from today.

**Comment by svanharmelen** [comment]
@djhojd please update to version 0.17.0 which fixes this regression. Sorry for the inconvenience!
