### ISSUE TITLE
Syntax highlighting flickers for a second when any file is opened

### ISSUE THREAD

**Issue by mcandre** [kevinsawicki/monokai#43]
When I open a file in Atom, the colors flicker several times in the first second after opening.

Example files:

* https://github.com/mcandre/mcandre/blob/master/automata/automata.c
* https://github.com/mcandre/mcandre/blob/master/automata/automata.rb

Using Atom 0.186.0 on OS X 10.10.2.

**Comment by asantos3** [comment]
You are using an old version of Atom, I suggest updating to the latest - v0.191.0

**Comment by maxkfranz** [comment]
I see the same on 0.192.0 on Mac OS.

**Comment by svanharmelen** [comment]
@mcandre this should be fixed in the mean time. Can you confirm this is no longer an issue?

**Comment by mcandre** [comment]
Seems to be fixed!

On Wed, Aug 5, 2015 at 4:32 AM, Sander van Harmelen <
notifications@github.com> wrote:

> @mcandre <https://github.com/mcandre> this should be fixed in the mean
> time. Can you confirm this is no longer an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinsawicki/monokai/issues/43#issuecomment-127933672>
> .
>



-- 
Cheers,
Andrew

**Comment by svanharmelen** [comment]
Thanks for the feedback!
