### ISSUE TITLE
Remove Italic

### ISSUE THREAD

**Issue by limianwang** [kevinsawicki/monokai#48]
Hello,
I've been trying to google this, but I wasn't able to find out what the actual css/less class triggers the italic on function and parameters for Monokai Theme.

I want to disable all italic, is there anyway i can do that?

Thanks

**Comment by dragonxlwang** [comment]
remove all ``font-style: italic;`` in less files and it should be good to go. you are welcome to checkout my forked version dragonxlwang/monokai or install it in atom ``apm install dragonxlwang-monokai``
