### ISSUE TITLE
plist: string tag syntax coloring also colors part of the tag

### ISSUE THREAD

**Issue by szhu** [kevinsawicki/monokai#52]
Same issue as atom/language-property-list#1, which was determined to be a theme issue. The theme creator fixed it in atom/base16-tomorrow-dark-theme@a19edc8, might be worth looking at.

![screen shot 2015-07-06 at 4 26 30 pm](https://cloud.githubusercontent.com/assets/1570168/8535614/3c0b0958-23fc-11e5-9a38-971b7d3c3d6b.png)

**Comment by svanharmelen** [comment]
@szhu thanks for pointing it out! PR #58 adds the fix for this...
