### ISSUE TITLE
pink golang brackets

### ISSUE THREAD

**Issue by fgvutn** [kevinsawicki/monokai#60]
Hello,

I just upgraded to 0.17.0 and all my brackets ([, ]) when coding in Go (and only in Go) turned pink. Most likely this is an issue not with the Monokai theme, but rather has to do with me upgrading the [go-plus](https://atom.io/packages/go-plus) package. But I thought you might want to know nonetheless.

Adding
```
.bracket {
  color: @syntax-text-color;
}
```
to the index.less file solve the problem at least for Go and so far as I can tell hasn't impacted on other syntaxes.

thanks

**Comment by svanharmelen** [comment]
@fgvutn could you try installing the latest 'language-go' package (apm install language-go)?

It should work as expected with the latest versions of both these packages (their both updated today making the packages more inline with other language and theme packages).

**Comment by fgvutn** [comment]
hello @svanharmelen , I tried your suggestion: IT WORKED! Thanks.

note: I needed to reload Atom as well

**Comment by svanharmelen** [comment]
Yeah, it's a bit nasty that the language-go package comes bundled with Atom itself and the theme doesn't. So the theme will notice an update right away, where the language-go package will only notice it when you install it on top of the bundled version.

Let's leave this issue open until a new version of Atom is released, so others having the same issue can find the (temp) solution here as well.

Thx...

**Comment by svanharmelen** [comment]
I'll close this one now as Atom 1.0.5 is released with latest and greatest `language-go` package which makes these two packages play nice again...
