### ISSUE TITLE
.= has the same color as a string

### ISSUE THREAD

**Issue by tap52384** [kevinsawicki/monokai#62]
.= has the same color together as a string instead of the same color as a period that concatenates a string solo and an equals sign solo

**Comment by tap52384** [comment]
forgot to mention the language is PHP if it helps.

**Comment by svanharmelen** [comment]
@tap52384 a screenshot would be very helpful...

**Comment by tap52384** [comment]
<img width="767" alt="screenshot 2015-08-13 14 54 08" src="https://cloud.githubusercontent.com/assets/647983/9258748/3fddc89e-41cb-11e5-8005-4a04f60c9c69.png">

**Comment by svanharmelen** [comment]
@tap52384 version 0.18.0 should solve your problem in a nice and consistent way...
