### ISSUE TITLE
Highlighting function parameters

### ISSUE THREAD

**Issue by woutderooms** [kevinsawicki/monokai#64]
I recently switched from Sublime to Atom, both using the Monokai syntax highlighting. In Sublime function parameters were highlighted in orange, in Atom they are plain white.

Language: Javascript (ECMA 5)
Monokai version: 0.18.0
Atom Version: 1.0.19

**Comment by svanharmelen** [comment]
@woutderooms it seems I cannot reproduce your issue:

![image](https://cloud.githubusercontent.com/assets/4171547/10277856/45f01108-6b59-11e5-9a77-f9ff745b1e2d.png)

Could you post an example and some additional info so I can have a closer look?

**Comment by woutderooms** [comment]
@svanharmelen my mistake, it seems that it works as expected when the syntax is set to *Javascript*, but fails to highlight when using *Babel ES6 Javascript* (using the `language-babel` package)

Maybe it is related that package instead.

**Comment by svanharmelen** [comment]
@woutderooms thanks for the feedback! And indeed the language packages are responsible for assigning scopes to words/symbols that it turn are used by highlighting packages like Monokai.
