### ISSUE TITLE
PHP got confused by SQL

### ISSUE THREAD

**Issue by tap52384** [kevinsawicki/monokai#65]
![screenshot 2015-10-21 10 53 34](https://cloud.githubusercontent.com/assets/647983/10640265/fbd64ba6-77e1-11e5-87b5-c26d4a97c135.png)

For whatever reason, the PHP syntax highlighting fails based on how crazy my SQL query is. In fact, the syntax is valid as the page loads.

**Comment by svanharmelen** [comment]
@tap52384 I would say this is related to the PHP language package as that one assigns the scopes. This package only gives the assigned scopes it's colours. So if you use the debugger, I think it will show you the assigned scopes are not correct...

**Comment by tap52384** [comment]
I'm not sure I understand you mean. Are you saying that the issue is not with this theme, but with a built-in package for Atom? Also, when you mention a debugger, are you talking about a debugger for the Atom text editor itself or something else? If you are referring to a PHP debugger, I'm not using one that integrates with Atom at the moment. I only have the core packages installed.

**Comment by svanharmelen** [comment]
@tap52384 sorry, I will be a little more verbose :wink:

In the end Atom is build on top of Chromium. So if you press (on OSX) `OPTION+CMD+i` it will open the same `Developer Tools` as you'll find in the Chrome browser. Once you've done that you can inspect the source HTML generated by all different packages resulting in what you see in Atom.

The language packages (for PHP that would be this package: https://atom.io/packages/language-php) are responsible for assigning scopes to all the different parts that make up the syntax (vars, funcs, consts e.d) and the theme packages (like this package) are them assigning colours to those scopes.

So indeed I'm suggesting this is a problem with the language package as I suspect it doesn't handle that specific (corner) case correctly and so assigns the wrong scope...

Makes sense?

**Comment by tap52384** [comment]
Yes, that does make sense. Thanks for taking the time to explain. Atom and this theme is awesome. It's because of this theme that I even tried changing from Sublime Text 3 and I'm so glad I did.

**Comment by svanharmelen** [comment]
@tap52384 I think there already is a issue logged for this with the PHP language package: https://github.com/atom/language-php/issues/52

So closing this one for now, but of course you can always reopen it when the language package part is fixed and you still see the issue.
