### ISSUE TITLE
Inconsistent line heights

### ISSUE THREAD

**Issue by ilikebits** [kevinsawicki/monokai#66]
See the following two screenshots, taken under Atom Dark and Monokai with identical plugins. Notice how the text is misaligned with the cursor and gutter line number in the Monokai screenshot.
![monokai](https://github-cloud.s3.amazonaws.com/assets%2F2092654%2F10956727%2Fbc4ba2c4-8312-11e5-9616-59c20a19192d.png)
![atom-dark](https://github-cloud.s3.amazonaws.com/assets%2F2092654%2F10956726%2Fbc4a3c04-8312-11e5-8159-c0f302197d35.png)

**Comment by sadovnychyi** [comment]
![image](https://cloud.githubusercontent.com/assets/193864/10960749/6ac027f4-83c1-11e5-8d0d-c767d04b9747.png)
Looks OK for me.

**Comment by ilikebits** [comment]
It doesn't occur for me on all lines, but I'm not sure what the correct conditions are. I've definitely seen this occur on other code before. If you look closely at my Monokai screenshot, you can see breaks in the indentation guide. Not sure what kind of styling would cause that, but this still occurs even with all community plugins disabled.

**Comment by ilikebits** [comment]
Played around with it for a bit longer and it turns out this is because of my font! See https://github.com/chrissimpkins/Hack/issues/111 for all the issues from an old version of the Hack font. Closing issue, sorry for the noise.
