### ISSUE TITLE
No colors in 0.19.0

### ISSUE THREAD

**Issue by ricardograca** [kevinsawicki/monokai#81]
Just updated to the latest version (0.19.0) and colors are gone:

![captura de ecra de 2017-01-29 19-59-51](https://cloud.githubusercontent.com/assets/1457035/22407406/ae2a10a4-e65d-11e6-851d-303cc61a2b47.png)

:sob: 

PS: Atom 1.12.9

**Comment by lcaparroz** [comment]
It's happening the same with me, just updated and it failed to show colours. I noticed that the *atom-monokai* (https://atom.io/themes/atom-monokai), just after the update.

**Comment by cvharris** [comment]
Same...just installed it brand new

**Comment by ricardograca** [comment]
This was due to a fix for Atom 0.13.0 which didn't keep backwards compatibility: #78. I can submit a PR with a "fix" for the "fix" :)

**Comment by ncarreiro** [comment]
That would be amazing, @ricardograca! I'll wait for this fix to be merged, thank you :)

**Comment by SATOFish** [comment]
I forgot to update "atom": ">0.39.0" to "atom": ">=1.13.0".
If you were using Atom versions 1.12.9 or earlier, I want to say "I'm very sorry". #82 

---
If you want to use it now please uninstall version 0.19.0. and
```
$ apm install monokai@0.18.0
```
Perhaps an update is displayed for for several days, but please don't update.

**Comment by ricardograca** [comment]
That works :+1:

**Comment by ncarreiro** [comment]
Thank you @SATOFish! When should we update? There would be a message in the Changelog that describes the fix of this bug? :)

**Comment by ricardograca** [comment]
@ncarreiro No. There won't be a "fix". Users of Atom < 1.13.0 will stay with Monokai 0.18.0 forever. The new 0.19.0 version is only compatible with Atom version 1.13.0 and newer.

**Comment by tavorag** [comment]
I have no issues, Atom-> up to date and the package too
