### ISSUE TITLE
Why is the theme different from the screenshot?

### ISSUE THREAD

**Issue by midgethoen** [kevinsawicki/monokai#98]
I installed and activated the theme. 

the syntax colours did change, but they are not the same:

<img width="1192" alt="screen shot 2017-12-13 at 18 17 42" src="https://user-images.githubusercontent.com/4599476/33952437-0e4903c2-e032-11e7-9946-89194da2f382.png">

Am I missing something here, is the README image outdated, or is something wrong with my installation?

**Comment by gustavoalfaro** [comment]
Yes, the README image is outdated, but I also notice that your theme is little bit weird the constants outside the render method shouldn't be on that color, only if they're on uppercase are purple, are you using javascript syntax instead of Babel ?

**Comment by gustavoalfaro** [comment]
This is the best syntax if you are working with ES6 
![image](https://user-images.githubusercontent.com/21284308/33968759-4967ac2c-e02f-11e7-973c-f58ec962858e.png)

**Comment by midgethoen** [comment]
> Yes, the README image is outdated

Allright then. It puzzled me for a little bit because I was looking for the -- original, I guess -- monokai theme.

> but I also notice that your theme is little bit weird the constants outside the render method shouldn't be on that color, only if they're on uppercase are purple, are you using javascript syntax instead of Babel ?

I was using `atom-ide` and `ide-typescript` when I took that screenshot. 
for reference, in case you want to troubleshoot this further, a screen shot with `language-babel` installed:

<img width="672" alt="screen shot 2017-12-14 at 09 31 23" src="https://user-images.githubusercontent.com/4599476/33982703-bc576f38-e0b1-11e7-845b-5c812dc99a06.png">
